/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ConexionBD;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Usuario
 */
public class Graficas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Graficas
     */
    private ConexionBD conexion;
    public Graficas() {
        initComponents();
        conexion=new ConexionBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fecha1 = new com.toedter.calendar.JDateChooser();
        fecha2 = new com.toedter.calendar.JDateChooser();
        panel = new javax.swing.JPanel();
        btnGrafica = new javax.swing.JButton();

        Fecha1.setDateFormatString("dd-MMM-yyyy");

        fecha2.setDateFormatString("dd-MMM-yyyy");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        btnGrafica.setText("Graficar");
        btnGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(btnGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(Fecha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaActionPerformed
        panel.removeAll();
        panel.repaint();
        Date fechaInicio=Fecha1.getDate();
        Date fechaFin=fecha2.getDate();
        SimpleDateFormat formato=new SimpleDateFormat("dd-MMM-yyyy");
        String fechaC=formato.format(fechaInicio);
        String fechaf=formato.format(fechaFin);
        estadistica(fechaC,fechaf);
    }//GEN-LAST:event_btnGraficaActionPerformed

    public void estadistica(String fechac,String fechaf){
        try {
            LinkedList datosAGraficar = new LinkedList();
            String sql="select fac_fecha,sum(fac_codigo) " +
                    "from fer_facturas " +
                    "where fac_fecha>'"+fechac+"' and fac_fecha<'"+fechaf+"' and FAC_ESTADO=1 " +
                    "group by fac_fecha " +
                    "order by 1";
            conexion.Conectar();
            Statement sta=conexion.getConexion().createStatement();
            ResultSet res=sta.executeQuery(sql);
            while(res.next()){
                 LinkedList aux = new LinkedList();
                    aux.add(res.getString(1));
                    aux.add(res.getString(2));
                    datosAGraficar.add(aux);
                    
            } 
        Iterator it=datosAGraficar.iterator();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        while (it.hasNext()) {
          LinkedList data = (LinkedList) it.next();
          dataset.setValue(Integer.parseInt(data.get(1).toString()),
          "Ganancias", data.get(0).toString());
        }
        JFreeChart chart = ChartFactory.createBarChart(
        "GANANCIAS DE VENTAS",
        "Fechas",
        "Ganancias en Dolares",
        dataset,
        PlotOrientation.HORIZONTAL,
        true,
        false,
        false
        );
        /*chart.setBackgroundPaint(Color.cyan);
        chart.getTitle().setPaint(Color.black); 
        CategoryPlot p = chart.getCategoryPlot(); 
        p.setRangeGridlinePaint(Color.blue); 
        ChartFrame frame = new ChartFrame("Estadisticas", chart);
        frame.pack();
        frame.setVisible(true);*/
        CategoryPlot p = chart.getCategoryPlot(); 
        p.setDomainGridlinesVisible(true);
            ChartPanel panelg=new ChartPanel(chart);
            panelg.setBounds(5, 10, 600, 500);
            panel.add(panelg);
            panel.repaint();
        
        }catch(Exception e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha1;
    private javax.swing.JButton btnGrafica;
    private com.toedter.calendar.JDateChooser fecha2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
